object NotificationCommand "zammad-notification" {
  command = [ "/usr/local/bin/notify_zammad" ]
  arguments += {
    "--zammad-hostname" = "192.168.100.209" // Change from localhost to this
    "--zammad-port" = "8080"
    "--token" = "A2aWateJaaAHYVLwTLupgNrJbbTlPpeqJ6CI2Maklem9TgVsXQhTpyGlYwJZyqw3"
    "--notification-type" = "$notification.type$"
    "--host-name" = "$host.name$"
    "--service-name" = "$service.name$"
    "--check-state" = "$service.state$"
    "--check-output" = "$service.output$"
    "--zammad-group" = "Users"
    "--zammad-customer" = "fetaje4253@kaoing.com"
  }
}
apply Notification "zammad-service" to Service {
  command = "zammad-notification"
  states = [ OK, Warning, Critical, Unknown ]
  types = [ Problem, Acknowledgement, Recovery ]
  
  /* Adding this satisfies the 'No users specified' error */
  user_groups = [ "icingaadmins" ]
  
  assign where host.name
}
